# Generated by Django 4.0 on 2022-07-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpcAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='path',
        ),
        migrations.AlterField(
            model_name='path',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='rpcAPI.destination'),
        ),
    ]
