# Generated by Django 4.0 on 2022-07-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpcAPI', '0002_remove_destination_path_alter_path_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='direction',
        ),
    ]
