# Generated by Django 4.0 on 2022-07-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpcAPI', '0003_remove_path_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='rpcAPI.destination'),
        ),
        migrations.AddField(
            model_name='path',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
