# Generated by Django 4.0 on 2022-07-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpcAPI', '0004_path_destination_path_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='rpcAPI.destination'),
        ),
    ]
