# Generated by Django 3.1.1 on 2023-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perpetrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('offence', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'perpetrator',
            },
        ),
    ]
